# Ubuntu 20.04 image with NVIDIA CUDA11.2 CUDNN8 + OpenGL and ROS Noetic
FROM cudnnnvidia_ros:latest

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# Install Git
RUN apt-get update && apt-get install -y git
 
# Create a Catkin workspace and clone TurtleBot3 repos
RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p /catkin_ws/src \
 && cd /catkin_ws/src \
 && catkin_init_workspace \
 && git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3.git \
 && git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git \
 && git clone https://github.com/leggedrobotics/darknet_ros.git \
 && cd /catkin_ws/src/darknet_ros \
 && git submodule update --init --recursive \
 && apt install wget \
# && cd catkin_workspace/src/darknet_ros/darknet_ros/yolo_network_config/weights/ \
# && wget http://pjreddie.com/media/files/yolov2.weights \
# && wget http://pjreddie.com/media/files/yolov2-tiny.weights \
# && wget http://pjreddie.com/media/files/yolov2-voc.weights \
# && wget http://pjreddie.com/media/files/yolov2-tiny-voc.weights \
# && wget http://pjreddie.com/media/files/yolov3-tiny.weights \
# && wget http://pjreddie.com/media/files/yolov3.weights \
# RUN echo "export TURTLEBOT3_MODEL=waffle_pi" >> ~/.bashrc
 

 
